spring:
  profiles:
    active: @activated.properties@  # Maven动态替换 ${profiles.active}

  # 通用配置（所有环境共享）
#  security:
#    basic:
#      enabled: false
#  management:
#    security:
#      enabled: false
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration