server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: never # always
#      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

#  data:
#    redis:
#      host: localhost
#      password:
#      port: 6379
#      database: 0

logging:
  level:
    com.example.demo: debug
    org.springframework.web: debug
    org.hibernate: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

app:
  jwt:
    secret: "MySuperSecretKeyThatIsAtLeast32BytesLong!"
    expiration: 86400000

cors:
  allowed-origins: http://localhost:3000,http://192.168.0.104:3000